name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          FITBIT_CLIENT_ID: ${{ secrets.FITBIT_CLIENT_ID }}
        run: |
          echo "const config = { CLIENT_ID: '$FITBIT_CLIENT_ID', REDIRECT_URI: 'https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}' };" > config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . 