# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create config.js
        env:
          FITBIT_CLIENT_ID: ${{ secrets.FITBIT_CLIENT_ID }}
        run: |
          echo "// Fitbit API Configuration" > config.js
          echo "window.config = {" >> config.js
          echo "    // Client ID loaded from GitHub Secrets" >> config.js
          echo "    CLIENT_ID: '${{ secrets.FITBIT_CLIENT_ID }}'," >> config.js
          echo "    // The redirect URI must match exactly what you registered in your Fitbit app settings" >> config.js
          echo "    REDIRECT_URI: 'https://askjarv.github.io/walktowhereyouwant/callback.html'" >> config.js
          echo "};" >> config.js

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4