name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Create config.js
        env:
          FITBIT_CLIENT_ID: ${{ secrets.FITBIT_CLIENT_ID }}
        run: |
          echo "// Configuration for the Fitbit API" > config.js
          echo "window.config = {" >> config.js
          echo "    CLIENT_ID: '${{ secrets.FITBIT_CLIENT_ID }}'," >> config.js
          echo "    REDIRECT_URI: 'https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}'" >> config.js
          echo "};" >> config.js

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Delete old workflows
        run: |
          # Delete old workflow files except the current one
          find .github/workflows -type f ! -name 'deploy.yml' -delete